"""Project-wide constants."""

PACKAGE_NAME = "django-migration-inspector"
REPORT_SCHEMA_VERSION = "1.3"
DEFAULT_DATABASE_ALIAS = "default"
DEFAULT_DEPENDENCY_HOTSPOT_LIMIT = 5
MIN_SUPPORTED_DJANGO_VERSION = (4, 2)
MAX_SUPPORTED_DJANGO_VERSION_EXCLUSIVE = (6, 0)
