"""Integration tests for visual graph renderers."""

from __future__ import annotations

from io import StringIO

from django.core.management import call_command
from pytest_django.plugin import DjangoDbBlocker


def test_management_command_renders_mermaid(django_db_blocker: DjangoDbBlocker) -> None:
    output = StringIO()

    with django_db_blocker.unblock():
        call_command("migration_inspect", "--format", "mermaid", stdout=output)

    rendered = output.getvalue()
    assert rendered.startswith("%% Generated by Django Migration Inspector\n")
    assert "flowchart TD" in rendered
    assert 'node_inventory_0001_initial["inventory.0001_initial"]' in rendered
    assert "node_inventory_0001_initial --> node_inventory_0002_add_sku" in rendered
    assert "classDef merge" in rendered


def test_management_command_renders_dot(django_db_blocker: DjangoDbBlocker) -> None:
    output = StringIO()

    with django_db_blocker.unblock():
        call_command("migration_inspect", "--format", "dot", stdout=output)

    rendered = output.getvalue()
    assert rendered.startswith("digraph migration_graph {\n")
    assert '"inventory.0001_initial" -> "inventory.0002_add_sku";' in rendered
    assert 'shape="diamond"' in rendered
