"""Graphviz DOT renderer for migration graph visualization."""

from __future__ import annotations

from dataclasses import dataclass

from django_migration_inspector.domain.keys import MigrationNodeKey
from django_migration_inspector.domain.reports import GraphInspectionReport

from .common import build_multiple_head_key_set, build_visible_edges, escape_dot_label


@dataclass(slots=True)
class DotGraphReportRenderer:
    """Render the visible migration graph as Graphviz DOT."""

    def render(self, report: GraphInspectionReport) -> str:
        """Render the graph inspection report as DOT."""

        multiple_head_keys = build_multiple_head_key_set(report)
        root_keys = frozenset(report.root_nodes)
        leaf_keys = frozenset(report.leaf_nodes)
        merge_keys = frozenset(report.merge_nodes)

        lines = [
            "digraph migration_graph {",
            (
                "  // Generated by Django Migration Inspector "
                f"(database={report.database_alias}, "
                f"scope={report.selected_app_label or 'all-apps'})"
            ),
            '  graph [rankdir="LR"];',
            '  node [shape="box", style="rounded", color="#334155", fontname="Helvetica"];',
            '  edge [color="#64748b"];',
        ]

        for node in report.nodes:
            attributes = self._build_node_attributes(
                migration_key=node.key,
                is_root=node.key in root_keys,
                is_leaf=node.key in leaf_keys,
                is_merge=node.key in merge_keys,
                is_conflict_head=node.key in multiple_head_keys,
            )
            lines.append(f'  "{escape_dot_label(node.key.identifier)}" [{", ".join(attributes)}];')

        for dependency, target in build_visible_edges(report):
            dependency_label = escape_dot_label(dependency.identifier)
            target_label = escape_dot_label(target.identifier)
            lines.append(f'  "{dependency_label}" -> "{target_label}";')

        lines.append("}")
        return "\n".join(lines) + "\n"

    def _build_node_attributes(
        self,
        *,
        migration_key: MigrationNodeKey,
        is_root: bool,
        is_leaf: bool,
        is_merge: bool,
        is_conflict_head: bool,
    ) -> list[str]:
        attributes = [f'label="{escape_dot_label(migration_key.identifier)}"']
        style_parts = ["rounded"]

        if is_merge:
            attributes.append('shape="diamond"')
            style_parts.append("filled")
            attributes.append('fillcolor="#ffedd5"')
            attributes.append('color="#c2410c"')

        if is_conflict_head:
            style_parts.append("filled")
            attributes.append('fillcolor="#fee2e2"')
            attributes.append('color="#b91c1c"')
        elif is_leaf:
            style_parts.append("filled")
            attributes.append('fillcolor="#dcfce7"')
            attributes.append('color="#15803d"')
        elif is_root:
            style_parts.append("filled")
            attributes.append('fillcolor="#dbeafe"')
            attributes.append('color="#1d4ed8"')

        deduped_style_parts = list(dict.fromkeys(style_parts))
        attributes.append(f'style="{",".join(deduped_style_parts)}"')
        return attributes
