"""Mermaid renderer for migration graph visualization."""

from __future__ import annotations

from dataclasses import dataclass

from django_migration_inspector.domain.keys import MigrationNodeKey
from django_migration_inspector.domain.reports import GraphInspectionReport

from .common import (
    build_mermaid_node_id,
    build_multiple_head_key_set,
    build_visible_edges,
    escape_mermaid_label,
)


@dataclass(slots=True)
class MermaidGraphReportRenderer:
    """Render the visible migration graph as Mermaid flowchart syntax."""

    def render(self, report: GraphInspectionReport) -> str:
        """Render the graph inspection report as Mermaid."""

        multiple_head_keys = build_multiple_head_key_set(report)
        lines = [
            "%% Generated by Django Migration Inspector",
            f"%% database={report.database_alias}",
            f"%% scope={report.selected_app_label or 'all-apps'}",
            "flowchart TD",
        ]

        for node in report.nodes:
            node_id = build_mermaid_node_id(node.key)
            node_label = escape_mermaid_label(node.key.identifier)
            lines.append(f'    {node_id}["{node_label}"]')

        for dependency, target in build_visible_edges(report):
            dependency_id = build_mermaid_node_id(dependency)
            target_id = build_mermaid_node_id(target)
            lines.append(f"    {dependency_id} --> {target_id}")

        style_lines = self._build_style_lines(report=report, multiple_head_keys=multiple_head_keys)
        if style_lines:
            lines.append("")
            lines.extend(style_lines)

        return "\n".join(lines) + "\n"

    def _build_style_lines(
        self,
        *,
        report: GraphInspectionReport,
        multiple_head_keys: frozenset[MigrationNodeKey],
    ) -> list[str]:
        lines = [
            "    classDef root fill:#dbeafe,stroke:#1d4ed8,stroke-width:1px;",
            "    classDef leaf fill:#dcfce7,stroke:#15803d,stroke-width:1px;",
            "    classDef merge fill:#ffedd5,stroke:#c2410c,stroke-width:2px;",
            "    classDef conflict fill:#fee2e2,stroke:#b91c1c,stroke-width:2px;",
        ]

        root_line = self._build_class_assignment("root", report.root_nodes)
        leaf_line = self._build_class_assignment("leaf", report.leaf_nodes)
        merge_line = self._build_class_assignment("merge", report.merge_nodes)
        conflict_line = self._build_class_assignment("conflict", tuple(sorted(multiple_head_keys)))

        for class_line in (root_line, leaf_line, merge_line, conflict_line):
            if class_line is not None:
                lines.append(class_line)

        return lines

    def _build_class_assignment(
        self,
        class_name: str,
        migration_keys: tuple[MigrationNodeKey, ...],
    ) -> str | None:
        if not migration_keys:
            return None

        node_ids = ", ".join(
            build_mermaid_node_id(migration_key) for migration_key in migration_keys
        )
        return f"    class {node_ids} {class_name};"
